# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Elate Edited"
license = "MIT"
licenselink = "https://github.com/saey55/hugo-elate-theme/blob/master/LICENSE.md"
description = "Elate theme ported to Hugo by Pieter Saey"
homepage = "https://github.com/RichardLitt/hugo-elate-theme/"
tags = ["Elate", "Hugo", "parallax"]
features = ["", "", ""]
min_version = 0.17

[author]
  name = "Richard Littauer"
  homepage = "https://burntfen.com"

[original]
  name = "Elate"
  homepage = "https://freehtml5.co/elate-free-html5-bootstrap-template/"
